name         'opentable-logstash_kafka'
version '0.1.4'
source       'git://github.com/opentable/puppet-logstash_kafka.git'
author       'opentable'
summary      'Module for managing the installation the kafka plugin for logstash'
description  'Install logstash-kafka plugin to allow you to use kafka as a input/output to/from logstash'
project_page 'https://github.com/opentable/puppet-logstash_kafka'
license      'MIT'
dependency    'puppetlabs/stdlib', '>=3.0.0'
